apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: blog-demo
    serviceType: nginx
spec:
  revisionHistoryLimit: 3
  minReadySeconds: 20
  progressDeadlineSeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 0%
  replicas: 2
  selector:
    matchLabels:
      serviceType: nginx
  template:
    metadata:
      labels:
        serviceType: nginx
        app: blog-demo
    spec:
      containers:
      - name: nginx
        securityContext:
          runAsUser: 100
        readinessProbe:
          httpGet:
            path: /_/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /_/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        image: registry.gitlab.com/obtao/blog-demo/nginx:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 64Mi
