# Default values for tango-base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"
minikube: true
homeDir: /home/ubuntu

system: SW-infrastructure
subsystem: tango-base
telescope: SKA-mid

tangodb:
  enabled: true
  use_pv: false
  component: tangodb
  function: tango-device-configuration
  domain: tango-configuration
  intent: production
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-db
    tag: 10.4.10
    pullPolicy: IfNotPresent
  db:
    rootpw: secret
    db: tango
    user: tango
    password: tango
  resources:
    requests:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 1Gi
    limits:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 2Gi
  livenessProbe:
    enabled: false
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    enabled: false
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

databaseds:
  enabled: true
  # domain tag was the .Release.Name set it as default empty
  # so that the old behaviour can still happen in the chart
  component: databaseds
  function: tangodb-interface
  domain: tango-configuration
  domainTag:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-cpp
    tag: 9.3.3
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem
      ephemeral-storage: 512Mi
    limits:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 1Gi
  livenessProbe:
    enabled: false
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    enabled: false
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

itango:
  enabled: false
  component: itango-console
  function: generic-tango-console
  domain: interactive-testing
  intent: enabling
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-itango
    tag: 9.3.1
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m     # 00m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem
      ephemeral-storage: 512Mi
    limits:
      cpu: 100m     # 00m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem
      ephemeral-storage: 512Mi

tangotest:
  enabled: false
  component: testdevice
  function: tango-client-validation-testing
  domain: interactive-testing
  intent: enabling
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-java
    tag: 9.3.3
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 1Gi
    limits:
      cpu: 500m     # 500m = 0.5 CPU
      memory: 512Mi # 512Mi = 0.5 GB mem
      ephemeral-storage: 1Gi

jive:
  enabled: false
  component: jive-gui
  function: generic-tango-jive-gui
  domain: interactive-testing
  intent: enabling
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-java
    tag: 9.3.3
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 256Mi
    limits:
      cpu: 500m     # 500m = 0.5 CPU
      memory: 512Mi # 512Mi = 0.5 GB mem
      ephemeral-storage: 256Mi

vnc:
  enabled: false
  component: vnc-gui
  function: generic-tango-vnc-gui
  domain: interactive-testing
  intent: enabling
  nodeport_enabled: false
  nodeport_vnc: 32081
  nodeport_novnc: 32082
  replicas: 3
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-vnc
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 256Mi
    limits:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 256Mi

vscode:
  enabled: false
  component: vscode-remote
  function: remote-developement
  domain: interactive-testing
  intent: enabling
  nodeport_enabled: false
  nodeport: 32080
  replicas: 1
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-vscode
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 256Mi
    limits:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 256Mi

tangorest:
  enabled: false
  replicas: 1
  component: tango-rest
  function: tango-http-interface
  domain: tango-configuration
  intent: enabling
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-rest
    tag: 1.14
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 256Mi
    limits:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 256Mi

logviewer:
  enabled: false
  component: logviewer
  function: tango-log-inspection
  domain: interactive-testing
  intent: enabling
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-java
    tag: 9.3.3
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem
      ephemeral-storage: 256Mi
    limits:
      cpu: 100m     # 100m = 0.1 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
      ephemeral-storage: 256Mi

# Configure Ingress resource that allow you to access the Tango REST API
ingress:
  enabled: false
  hostname: tango-base.minikube.local

  # Ingress annotations
  annotations:
    kubernetes.io/ingress.class: traefik

  # Ingress TLS configuration
  #
  tls:
    enabled: false
    secretname: "tls-secret-tango-base-{{ .Release.Name }}"
    hostname: "{{ .Values.ingress.hostname }}"


nodeSelector: {}

affinity: {}

tolerations: []
