# reff: https://github.com/IBM/cloud-native-starter/blob/master/security/articles-secure/deployment/articles-sa.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: articles
  namespace: default
  labels:
    app: articles
spec:
  selector:
    matchLabels:
      app: articles
  replicas: 1
  template:
    metadata:
      annotations: 
        sidecar.istio.io/inject: "true"    
      labels:
        app: articles
        version: v1
    spec:
      serviceAccountName: articles
      containers:
      - name: articles
        image: docker.io/haraldu/articles:secure-v1
        imagePullPolicy: Always  
        ports:
        - containerPort: 8082
        env:
        - name: QUARKUS_OIDC_AUTH_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: security-url-config
              key: QUARKUS_OIDC_AUTH_SERVER_URL