name: Fuzz test

on: 
  push:
    branches:
      - main
    pull_request:
      brancehs:
        - main
        
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          python-version: '3.x'
      - name: Run fuzz test
        run: python fuzz.py
