name: Fuzz test

on: 
  push:
    branches:
      - main
    pull_request:
      brancehs:
        - main
        
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run fuzz test
        run: python Fuzz.py
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: fuzz-report
          path: fuzz_report.txt
